name: gazachat
description: "gaza chat is a cross-platform messaging app that allows users to communicate with each other in real-time. It is designed to be fast, secure, and easy to use, with features such as group chats, voice and video calls, and file sharing. The app is built using Flutter, a popular open-source framework for building mobile apps, and is available for both iOS and Android devices."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 0.4.3+45
license: MIT

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # fonts 
  google_fonts: ^6.2.1
  # responsive design
  flutter_screenutil: ^5.9.3
  logger: ^2.6.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  qr_flutter: ^4.1.0
  flutter_blue_plus: ^1.35.5
  ai_barcode_scanner: ^7.0.0
  emoji_picker_flutter: ^4.3.0
  # state management
  flutter_riverpod: ^2.6.1
  json_serializable: ^6.10.0
  build_runner: ^2.6.0
  location: ^8.0.1
  uuid: ^4.5.1
  lottie: ^3.3.1
  flutter_spinkit: ^5.2.1
  package_info_plus: ^8.3.0
  nearby_connections: ^4.3.0
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0
  flutter_flip_card: ^0.0.6
  screenshot: ^3.0.0
  share_plus: ^11.0.0
  gal: ^2.3.2
  easy_localization: ^3.0.8
  flutter_localization: ^0.3.3
  url_launcher: ^6.3.2
  timezone: ^0.10.1
  flutter_local_notifications: ^19.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0
  android_notification_icons: ^0.0.1
  flutter_lints: ^5.0.0

android_notification_icons:
  image_path: 'assets/icons/logo_app_black.png' # required

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/
    - assets/icons/
    - assets/translations/

